### ISSUE TITLE
gui button object mistreats min-height specification

### ISSUE THREAD

**Issue by paschlie** [racket/gui#163]
#lang racket/gui

; The following demonstrates a bug, where the gui buttion object does not properly treat its
; min-height specification as min-height of the drawn button-object, instead it appears to treat
; it as the min-height of the drawn-object + its vert-margin; which is wrong; although its parent
; will determine its child's effective minium height will be its (min-height + 2 * vert-margin).
; Nor does it appear to understand how to increase the min-height required to host multiple
; lines of text.

; Create a dialog box
(define dialog (instantiate dialog% ("Example")))

; Add a horisonal panel, centered within the dialog box
(define hpanel-1
(new horizontal-panel% [parent dialog]
[alignment '(center center)]))
; Add buttons within the horizonal panel having a minium height of 80 pixels (bug!)
(new button% [parent hpanel-1] [min-height 80] [label "a b/c\rdms"])
(new button% [parent hpanel-1] [min-height 80] [label "sin\racos"])
(new button% [parent hpanel-1] [min-height 80] [label "cos\racos"])
(new button% [parent hpanel-1] [min-height 80] [label "tan\ratan"])

; Add another horisonal panel, centered within the dialog box
(define hpanel-2
(new horizontal-panel% [parent dialog]
[alignment '(center center)]))
; Add buttons within the horizonal panel, having a minium height of 80 pixels (bug!)
(new button% [parent hpanel-2] [min-height 80] [label "X^Y\re^X"])
(new button% [parent hpanel-2] [min-height 80] [label "X^1/Y\rsqrt X"])
(new button% [parent hpanel-2] [min-height 80] [label "XvY\rln X"])
(new button% [parent hpanel-2] [min-height 80] [label "1/X"])

; Show the dialog
(send dialog show #t)

**Comment by mflatt** [comment]
Is this one Mac OS? If so, the sort answer is that you can get better results for now by using "\n" instead of "\r".

On Mac OS, the way the button is drawn is controlled by system libraries. The `racket/gui` layer can specify dimensions for a button, but the library decides how to use that space — and for the default button style, it will only draw the button as one-line tall, centered within the button's space.

When a string label includes "\n", then `racket/gui` requests a different style of button, and that button style takes up the specified space. Probably `racket/gui` should request that style for a label that contains "\r", too. And probably it should support an option to use that style no matter what the label is, so that the button with label "1/X" can be consistent with the others; otherwise, you have to create the button with a label containing "\n" and then use `set-label` to change to "1/X".

**Comment by paschlie** [comment]
Thank you Matthew,

Trying \n in lieu of \r didn’t occur to me, that produces the expected results for multi-line text by default;

but note "min-height" should enable the button’s min-height to be specified independently of whether it’s overridden by the height of the text label, as presently supported for "min-width".

(I’ve poked around in the source, but it’s not obvious to me where it's encoded.)

**Comment by mflatt** [comment]
I've added a `'multi-line` style to `button%` (so, available in future Racket versions) and enabled it when a string contains either "\n" (as before) or "\r" (new).

Unfortunately, there's no way with the Mac OS GUI libraries to make a button both use the system-standard look and make it stretch vertically. So, a programmer has to explicitly provide a hint on which of those two to prioritize. Currently, the only way to select the stretchable mode is providing a string that contains "\n", and the change adds "\r" and `'multi-line` as additional ways.

**Comment by paschlie** [comment]
Thank  you.
