### ISSUE TITLE
Insert method of racket:text% instances incorrectly replaces CRLF with LFLF and double-counts lines

### ISSUE THREAD

**Issue by Runi-c** [racket/gui#221]
![image](https://user-images.githubusercontent.com/5150427/112711533-c534bc80-8e8e-11eb-8dbd-38a15764b39a.png)

This is currently causing a bug in https://github.com/jeapostrophe/racket-langserver making it unusable with editors configured to use CRLF line endings. Since the line endings get double-counted, all symbol positions are reported incorrectly.

**Comment by jeapostrophe** [comment]
For context, the Racket LSP server works, basically, by running a "headless" DrRacket and having the edit events that VSCode/etc sends it affect that DrR and then we can just re-use all of the existing DrR functions for things like Check Syntax and so on

**Comment by rfindler** [comment]
I'm not sure we can change how `insert` works but there is support for CRLF and whatnot already. Did you look into using it? In addition to the stuff in [`editor<%>`](https://docs.racket-lang.org/gui/editor___.html?q=text%25#%28meth._%28%28%28lib._mred%2Fmain..rkt%29._editor~3c~25~3e%29._load-file%29%29) (also insert-port), DrRacket uses the [crlf-line-endings-mixin](https://docs.racket-lang.org/framework/Text.html?q=crlf#%28def._%28%28lib._framework%2Fmain..rkt%29._text~3acrlf-line-endings~3c~25~3e%29%29).

**Comment by rfindler** [comment]
I certainly can't say I understand the ramifications of making a change along the lines you are suggesting, but please interpret my comment about "can't change `insert`" to a comment about maintaining backwards compatibility. 

I don't know how the langserver is working and what levers we have available to us to pull here. I just meant to offer the suggestion that DrRacket does actually work on windows and there is more than one way to get stuff inserted into a text% and suggest that maybe there might be a different way to use it than what's currently being done. 

If someone wanted to share some more context I might be more useful and I'm sorry that all I can offer at this point is skepticism that changing the guts of `text%` is the right move (but that is my initial thinking).

**Comment by Runi-c** [comment]
To clarify, `insert-port` absolutely works and is a fine solution to the problem in the langserver specifically. I'm aware that DrRacket works on windows - this issue deals specifically with the `insert` method of `racket:text%` having incorrect behavior. The purpose of my previous comment was just to respond to your suggestions and add what info I learned from digging into this a bit.

I understand that backwards compatibility is important and the bug has workarounds, and though I'm not personally convinced that the bug is worth keeping (is there really meaningful software relying on the mutation of CRLF to LFLF and double-counting lines wrongly?), but we have a working solution on the langserver, so if the decision here is to keep the bug for compatibility then feel free to close the issue.

**Comment by alex-hhh** [comment]
I dont' think this is a bug in `racket:text%`.  Inside programs the convention is to use a single character for new lines, usually this is `\n`, but some programs also use `\r`.  So, **inside a program**, a string such as "a\r\nb" to me has two new lines in it.  The convention that "\r\n" is a single new line is only when data is stored in files.

Usually the line ending conversion happens when you read data from a file, by specifying that it is in text mode.  For example, if you put the "a..b..c" text in a file named "test.dat", with CRLF line endings, the result depends on how you read that file in, either in text mode or binary mode.

```
#lang racket
(require framework)

(define doc-text1 (new racket:text%))
(send doc-text1 insert (file->string "./test.dat" #:mode 'text))
(send doc-text1 get-text)

(define doc-text2 (new racket:text%))
(send doc-text2 insert (file->string "./test.dat" #:mode 'binary))
(send doc-text2 get-text)
```

I am not sure where does the lang-server gets the program text before inserting it in a `racket:text%` object, but if it is from a file, it should specify that the file is in "text mode".  If the data is obtained from other sources, it should also be normalized before adding it to the text...

**Comment by Runi-c** [comment]
The langserver is sent the program text as JSON from the client. So by the time the JSON is parsed it is just in a string. `(send doc-text insert-port (open-input-string str))` would therefore seem to be the go-to here.

I was not aware of this convention you're referring to. If such a convention exists then this behavior makes more sense.
