### ISSUE TITLE
Text color in the toolbar doesn't change

### ISSUE THREAD

**Issue by bmarvinb** [racket/gui#256]
Text color in the toolbar doesn't change after macOS dark/light theme changed. Every time when dark/light theme changes I should reload the entire editor, without this it doesn't work properly. For example after dark mode, text in light mode is still light, and doesn't change to dark.

**Comment by rfindler** [comment]
Here's the docs on the [`backgroundColor`](https://developer.apple.com/documentation/appkit/nswindow/1419751-backgroundcolor) method that's being called and it makes me wonder if `NSColor` somehow has to be more dynamic?

**Comment by rfindler** [comment]
Oops actually [this is the method being called](https://developer.apple.com/documentation/appkit/nscolor/1528630-windowbackgroundcolor).

**Comment by rfindler** [comment]
This one has been fixed by recent commits, notably https://github.com/racket/gui/commit/70dc167e63188b60758cae46cfc788ea726c0591 and https://github.com/racket/gui/commit/9682a952eb5742a0065ec18195bef7f4db7b7e25 but there is more work for similar stuff that was done recently (and probably more that still needs doing).
