### ISSUE TITLE
Add \nsubseteq LaTeX symbol to Dr. Racket

### ISSUE THREAD

**Issue by rxg** [racket/gui#303]
\nsubseteq would be well-mapped to Unicode U+2288 as per:
https://www.fileformat.info/info/unicode/char/2288/index.htm

and

https://www.tutorialspoint.com/tex_commands/nsubseteq.htm

At the same time, \subsetneq would be well-mapped to Unicode U+228A as per:

https://www.fileformat.info/info/unicode/char/228a/index.htm
and
https://www.tutorialspoint.com/tex_commands/subsetneq.htm

**Comment by rfindler** [comment]
It turns out that a change is typically needed to [this function (or somewhere nearby)](https://github.com/racket/scribble/blob/3085e982b102c0e70caa7f192023c6ed0ef6cbd2/scribble-lib/scribble/latex-render.rkt#L1296) for these changes. That's because DrRacket includes a list of all of them in its manual which gets built to PDF.
