### ISSUE TITLE
get-file-list GTK+3 Error Message

### ISSUE THREAD

**Issue by lehitoskin** [racket/gui#57]
I'm using gtk+-3.22.4 on Gentoo and I now see this error when I run `get-file-list`.

```
~> racket
Welcome to Racket v6.7.
> (require racket/gui)
> (get-file-list)
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
#f
>
```

**Comment by mflatt** [comment]
I think this message means "you shouldn't create a dialog without a parent frame", or more specifically in this case, "don't let the second argument to `get-file-list` default to #f".

I'm not sure there's anything that `racket/gui` can or should do to suppress the message, since it seems to be a commentary on the general idea of having a dialog without a parent.

**Comment by lehitoskin** [comment]
I see. Giving `get-file-list` a parent gets rid of this message. The warning never interfered with my code, but I figured I'd give the devs a shout out in case there was something more insidious.
